export default [
    {
        product_id: '0',
        product_name: '屹立塑胶',
        product_num: '5520U-1001',
        product_photo: require('../assets/img-product/product_photo0.png'),
        product_number: '6560',
        product_company: '东莞市xxxx有限公司',
        product_person: '负责人1',
        product_create_time: '2023-05-20 09:30:00',
        product_status: '0',
        product_detail: '一种抗子外线耐冲击化学药品'
    },
    {
        product_id: '1',
        product_name: '二溴新戊二醇',
        product_num: '3296-90-0',
        product_photo: require('../assets/img-product/product_photo1.png'),
        product_number: '28280',
        product_company: '浙江省xxxx有限公司',
        product_person: '负责人2',
        product_create_time: '2023-05-21 12:00:00',
        product_status: '0',
        product_detail: '一种反应性阻燃剂，使用后能达到更加严密的阻燃效果。'
    },
    {
        product_id: '2',
        product_name: '奥克泰式杀孢子剂',
        product_num: '4876-20-10',
        product_photo: require('../assets/img-product/product_photo2.png'),
        product_number: '998',
        product_company: '济南xxxx有限公司',
        product_person: '负责人3',
        product_create_time: '2023-05-22 07:30:00',
        product_status: '1',
        product_detail: '进口Oxytech杀孢子剂，过氧化氢浓缩液，细胞房无味杀孢子剂无毒。'
    },
    {
        product_id: '3',
        product_name: '安氧去除剂',
        product_num: 'Js-203',
        product_photo: require('../assets/img-product/product_photo3.png'),
        product_number: '8876',
        product_company: '江苏省xxxx有限公司',
        product_person: '负责人4',
        product_create_time: '2023-05-23 20:30:00',
        product_status: '0',
        product_detail: 'JS-203氨氮去除剂主要用于去除废水中的氨氮，投加后使废水中的氨氮部分生成不溶于水的氮气。'
    },
    {
        product_id: '4',
        product_name: '聚丙烯酰胺',
        product_num: '6374-19',
        product_photo: require('../assets/img-product/product_photo4.png'),
        product_number: '475',
        product_company: '任丘市xxxx有限公司',
        product_person: '负责人5',
        product_create_time: '2023-05-24 13:30:00',
        product_status: '1',
        product_detail: '江海聚丙酰胺，工业污水处理，乳液增稠，化学絮凝药剂。'
    },
    {
        product_id: '5',
        product_name: '氧化铝',
        product_num: 'Cls-234',
        product_photo: require('../assets/img-product/product_photo5.png'),
        product_number: '38',
        product_company: '河间市xxxx有限公司',
        product_person: '负责人6',
        product_create_time: '2023-05-25 15:30:00',
        product_status: '1',
        product_detail: '泰亨，饮水级氧化铝，水体净化水处理药剂。'
    },
    {
        product_id: '6',
        product_name: 'COD去除剂',
        product_num: '28366',
        product_photo: require('../assets/img-product/product_photo6.png'),
        product_number: '1033',
        product_company: '巩义市xxxx有限公司',
        product_person: '负责人7',
        product_create_time: '2023-05-26 16:30:00',
        product_status: '0',
        product_detail: 'cod去除剂是针对电镀、线路板等废水中COD的可生化性低而特别开发的一种新型药剂。'
    },
    {
        product_id: '7',
        product_name: '春雷霉素',
        product_num: '2432',
        product_photo: require('../assets/img-product/product_photo7.png'),
        product_number: '118',
        product_company: '青州xxxx有限公司',
        product_person: '负责人8',
        product_create_time: '2023-05-27 12:00:00',
        product_status: '1',
        product_detail: '一种有机化合物，用于农作物杀菌。'
    },
    {
        product_id: '8',
        product_name: '硫酸亚铁',
        product_num: '63546',
        product_photo: require('../assets/img-product/product_photo8.png'),
        product_number: '275',
        product_company: '巩义市xxxx有限公司',
        product_person: '负责人9',
        product_create_time: '2023-05-28 10:30:00',
        product_status: '0',
        product_detail: '一种无机物，可用于色谱分析剂、污水处理。'
    },
    {
        product_id: '9',
        product_name: '硝酸钠',
        product_num: '3532',
        product_photo: require('../assets/img-product/product_photo9.png'),
        product_number: '536',
        product_company: '巩义市xxxx有限公司',
        product_person: '负责人10',
        product_create_time: '2023-05-29 08:30:00',
        product_status: '0',
        product_detail: '白色晶体，易溶于水，可用于污水处理。'
    },
    {
        product_id: '10',
        product_name: '除垢剂',
        product_num: '2763-21',
        product_photo: require('../assets/img-product/product_photo10.png'),
        product_number: '2819',
        product_company: '成都市xxxx有限公司',
        product_person: '负责人11',
        product_create_time: '2023-05-30 19:00:00',
        product_status: '0',
        product_detail: '外观无色至淡黄色透明液体密度(20℃)/g·cm-3≥1.10pH。'
    },
    {
        product_id: '11',
        product_name: '石英石去黄皮药剂',
        product_num: '874-29',
        product_photo: require('../assets/img-product/product_photo11.png'),
        product_number: '588',
        product_company: '河南省xxxx有限公司',
        product_person: '负责人12',
        product_create_time: '2023-05-31 17:30:00',
        product_status: '1',
        product_detail: '石英石无害清洗剂,可有效石英矿石深层锈迹、黄斑、污渍。'
    },
]